### ISSUE TITLE
See: Allow BAR movement during boot and hotplug

### ISSUE THREAD

**Issue by morgoth6** [JuliaComputing/nvidia-driver-pcie-rebar#2]
Not sure is this a patch series mentioned in readme, but for reference take a look at: [Allow BAR movement during boot and hotplug](https://patchwork.kernel.org/project/linux-pci/cover/20201218174011.340514-1-s.miroshnichenko@yadro.com/) 
I used it for quite some time (laptop and few servers) without any bigger problems and it was quite easy to port for recent kernels as well.

**Comment by Keno** [comment]
Yes, the series is linked in the repo. The rebar patch to the Nvidia driver is still required with that series though, it just makes it more likely that the rebar will succeed to find free address space.

**Comment by morgoth6** [comment]
Maybe patch can be submitted to recently created  https://github.com/NVIDIA/open-gpu-kernel-modules ?

**Comment by Keno** [comment]
https://github.com/NVIDIA/open-gpu-kernel-modules/pull/3
